name: 7sungcola
permalink: :year/:month/:day/:title
baseurl: /jekyll-theme-diary

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2022.06
now: 2022.06
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : yourname@gmail.com
  github : 7sungcola
  twitter : 

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Diary: "/diary"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed